services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gameshelf
      POSTGRES_PASSWORD: gameshelf
      POSTGRES_DB: gameshelf
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://gameshelf:gameshelf@db:5432/gameshelf
    ports:
      - "8000:8000"
    
    restart: unless-stopped

volumes:
  pgdata: