services:
  api:
    build: 
    ports:
    environment:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gameshelf

volumes:
  pgdata: